results_dir: "OsteoDiffusion/optuna_runs/denoising_diffusion_latents/test_result"
model_path: "OsteoDiffusion/optuna_runs/denoising_diffusion_latents/test_result/model.pt"
diffusion_train_config: "OsteoDiffusion/configs/denoising_diffusion_latents/test_diffusion_config.yaml"
dataset_dir: "OsteoDiffusion/data/bones_dataset_subset"
dataset_data_file_name: "lumbopelvic_masked_normed_global_clip_resampled_32_32_32.npz"
